# fly.toml file generated for bot-box on 2023-04-18T09:44:51-04:00

app = "bot-box"
kill_signal = "SIGTERM"
kill_timeout = 5
primary_region = "ewr"
processes = []

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "bot-box.fly.dev"
  PORT = "8080"

[mounts]
  source="bb_data"
  destination="/data"

[experimental]
  auto_rollback = true

[[services]]
  autostart = true
  autostop = false
  http_checks = []
  internal_port = 4000
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s" # allow time for startup
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
